[package]
name = "cef"
description = "Use cef in Rust"

version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true

[features]
dox = ["cef-dll-sys/dox"]

[package.metadata.docs.rs]
features = [ "dox" ]

[dependencies]
cef-dll-sys.workspace = true

winit = { workspace = true }
wgpu = { workspace = true }
pollster = { workspace = true }
tracing-subscriber = { version = "0.3.19", features = ["env-filter"] }
tracing = "0.1.41"
bytemuck = { version = "1.23.1", features = ["derive"] }


[target.'cfg(target_os = "windows")'.dependencies]
windows-sys.workspace = true

[target.'cfg(target_os = "macos")'.dev-dependencies]
plist.workspace = true
serde.workspace = true

[[example]]
name = "simple_offscreen"
path = "examples/simple_offscreen.rs"

[[example]]
name = "winit_only"
path = "examples/winit_only.rs"

[[example]]
name = "minimal_test"
path = "examples/minimal_test.rs"


[[example]]
name = "offscreen_winit"
path = "examples/offscreen_winit.rs"

[[example]]
name = "cefsimple"
crate-type = [ "bin" ]
path = "examples/cefsimple/main.rs"

[[example]]
name = "cefsimple_helper"
crate-type = [ "bin" ]
path = "examples/cefsimple/mac/helper.rs"

[[example]]
name = "bundle_cefsimple"
crate-type = [ "bin" ]
path = "examples/bundle_cefsimple.rs"
